# Generated by Django 2.2.7 on 2020-07-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20200731_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfollows',
            name='follows',
        ),
        migrations.AddField(
            model_name='userfollows',
            name='following_user',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.DeleteModel(
            name='UserFollowers',
        ),
    ]
