# Generated by Django 2.2.7 on 2020-08-03 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20200731_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='following_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='network.UserFollows'),
        ),
    ]
