# Generated by Django 2.2.7 on 2020-08-03 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_post_following_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='following_user',
        ),
        migrations.AddField(
            model_name='post',
            name='user_follows',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.UserFollows'),
        ),
    ]
