# Generated by Django 2.2.7 on 2020-08-04 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20200803_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_follows',
        ),
    ]
