# Generated by Django 2.2.7 on 2020-08-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_auto_20200813_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='like_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
