# Generated by Django 2.2.7 on 2020-08-14 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_auto_20200813_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='like_count',
            new_name='post_id',
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.Likes'),
        ),
    ]
